import Head from "next/head";
import Button from "../components/builder/builder-components/Button";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Take Home Assignment</h1>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            width: "20%",
            justifyContent: "space-between",
            padding: "30px",
          }}
        >
          <Button
            title="Task 1"
            style={{
              backgroundColor: "#527CEA",
              height: "50px",
              width: "100px",
              color: "white",
            }}
            callback={() => {
              console.log("button from Builder1 pressed!");
              window.location.href = "/task-1";
            }}
          />
          <Button
            title="Task 2"
            style={{
              backgroundColor: "#527CEA",
              height: "50px",
              width: "100px",
              color: "white",
            }}
            href="/task-1"
          />
        </div>
        <h3>Zubin Choudhary</h3>
      </main>
    </div>
  );
}
